spring:
  h2:
    console:
      enabled: true
  application:
    name: offerGen
  datasource:
    url: jdbc:h2:mem:offerMaker
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  tomcat:
    connection-timeout: 30s
  servlet:
    session:
      cookie:
        max-age: 6s
      timeout: 30s
    context-path: /
  port: 8080
